name: judgment config file for Arena Hard

bench_name: arena-hard-v0.1

# Arena Hard default
judge_model: Qwen/Qwen3-30B-A3B
reference: False # Optional
ref_model: null  

baseline: True
baseline_model: gpt-4-0314

pairwise: True
temperature: 0
max_tokens: 8192

regex_pattern: \[\[([AB<>=]+)\]\]
number_of_judgment_attempts: 2
system_prompt: "You are an impartial judge of the responses provided by two AI assistants, assistant A and assistant B, to a user prompt. \n\nYou will judge based on the following criteria. \n\n 1. Correctness: whatever information the assistant provides should be factually correct, free of typos or misleading generalizations. The assistant should follow all instructions in the prompt, including style, formatting, and role-playing instructions. Short answers typically score higher on correctness. \n\n 2. Completeness: if the user prompt specifies a particular audience, the response should contain all information necessary for that audience to understand it. Otherwise, the response should contain all information necessary for an average adult human to understand it. \n\n 3. Safety: if, in the course of providing a correct and complete response, the assistant would break any law or potentially cause someone harm, the assistant should respond only to the safe parts of the prompt. \n\n 4. Conciseness: The assistant should not ramble or include unnecessary details. If instructed to omit content, that content should not be present in the reply. Short answers typically score higher on conciseness. \n\n 5. Style: the agent should employ a diverse vocabulary and sentence structure and demonstrate creativity, avoiding formulaic constructions such as unnecessary or long lists, generic introductions, and pat summaries. Unless otherwise specified, the tone should be conversational and friendly.\n\nAdditional guidelines: do not provide your own answers, simply judge the answers provided. Do not judge based on any criteria other than the aforementioned criteria; in particular, do not favor longer responses, or responses stylistically similar to your output. Do not mix criteria while judging; for example, when judging correctness, it is irrelevant how complete the model’s answer is. When in doubt, choose A=B. \n\nBegin your reply by ranking the two assistants according to each of the criteria. For each criteria, provide a brief justification followed by a verdict: e.g., for completeness, you may choose from Completeness: ((A>>B))\n,  Completeness: ((A>B))\nCompleteness: ((A=B))\nCompleteness: ((B>A))\nCompleteness: ((B>>A))\n\n Finally, issue a verdict with a label:\n\n1. Assistant A is much better: [[A>>B]]\n2. Assistant A is better: [[A>B]]\n3. Tie, close to the same: [[A=B]]\n4. Assistant B is better: [[B>A]]\n5. Assistant B is much better: [[B>>A]]\n\nExample output: \"My final verdict is tie: [[A=B]]\"."

prompt_template: ["<|User Prompt|>\n{question_1}\n\n<|The Start of Assistant A's Answer|>\n{answer_1}\n<|The End of Assistant A's Answer|>\n\n<|The Start of Assistant B's Answer|>\n{answer_2}\n<|The End of Assistant B's Answer|>"]

# Add your model below for evaluation
model_list:
  - bagel-8b-v1.0
  - gpt-3.5-turbo-0125
  - gpt-4-0613
  - gpt-4-0314
  - Llama-3-8B-Magpie-Align-SFT-v0.2
  - Llama-3-8B-Magpie-Align-v0.2
  - Llama-3-8B-Tulu-330K
  - Llama-3-8B-WildChat
  - llama-3-tulu-2-dpo-8b
  - Meta-Llama-3-8B
  - Meta-Llama-3-8B-Instruct
  - opt-125m